###############################################################################
#
# NanOS - LED blink example
#
# Configure your target platform below
#
###############################################################################

#------------------------------------------------------------------------------
# Target configuration
#------------------------------------------------------------------------------

# Name of the NanOS project
PROJECT = ledblink-example

# Defines the platform and variant
PLATFORM = arduino
VARIANT  = uno

# Define our own source files
SOURCES  = ledblink.c

# Include NanOS make file
include ../../NanOS.mk